name: Deploy to Hostinger Staging

on:
  push:
    branches:
      - englivision

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: englivision # Specifies the environment to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build:production
          mv ./dist/index.html ./dist/index.php
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: /home/u928593761/domains/engli-vision.com/public_html/library/
          SOURCE: ./dist/
